package il.tutorials.truegotham.model

enum class ImportStatus {
    IMPORTED,
    CRIME_CLASSIFICATION,
    SUMMARY_CREATION,
    COVER_IMAGE_GENERATION,
    LOCATION_EXTRACTION,
    OFFENDER_PROFILE_EXTRACTION,
    OFFENDER_PROFILE_IMAGE_GENERATION,
    OFFENSES_EXTRACTION,
    MOTIVATION_CREATION,
    EVIDENCE_RECOGNITION,
    FINALIZE,

    FINISHED,
    REMOVE_IRRELEVANT
}